from enum import Enum


class Symbol(Enum):
    T = "{T}"  # Tap this permanent
    Q = "{Q}"  # Untap this permanent
    E = "{E}"  # An energy counter
    PW = "{PW}"  # Planeswalker
    CHAOS = "{CHAOS}"  # Chaos
    A = "{A}"  # An acorn counter
    TK = "{TK}"  # A ticket counter
    X = "{X}"  # X generic mana
    Y = "{Y}"  # Y generic mana
    Z = "{Z}"  # Z generic mana
    _0 = "{0}"  # Zero mana
    _half = "{½}"  # One-half generic mana
    _1 = "{1}"  # One generic mana
    _2 = "{2}"  # Two generic mana
    _3 = "{3}"  # Three generic mana
    _4 = "{4}"  # Four generic mana
    _5 = "{5}"  # Five generic mana
    _6 = "{6}"  # Six generic mana
    _7 = "{7}"  # Seven generic mana
    _8 = "{8}"  # Eight generic mana
    _9 = "{9}"  # Nine generic mana
    _10 = "{10}"  # Ten generic mana
    _11 = "{11}"  # Eleven generic mana
    _12 = "{12}"  # Twelve generic mana
    _13 = "{13}"  # Thirteen generic mana
    _14 = "{14}"  # Fourteen generic mana
    _15 = "{15}"  # Fifteen generic mana
    _16 = "{16}"  # Sixteen generic mana
    _17 = "{17}"  # Seventeen generic mana
    _18 = "{18}"  # Eighteen generic mana
    _19 = "{19}"  # Nineteen generic mana
    _20 = "{20}"  # Twenty generic mana
    _100 = "{100}"  # One hundred generic mana
    _1000000 = "{1000000}"  # One million generic mana
    _inf = "{∞}"  # Infinite generic mana
    WU = "{W/U}"  # One white or blue mana
    WB = "{W/B}"  # One white or black mana
    BR = "{B/R}"  # One black or red mana
    BG = "{B/G}"  # One black or green mana
    UB = "{U/B}"  # One blue or black mana
    UR = "{U/R}"  # One blue or red mana
    RG = "{R/G}"  # One red or green mana
    RW = "{R/W}"  # One red or white mana
    GW = "{G/W}"  # One green or white mana
    GU = "{G/U}"  # One green or blue mana
    BGP = "{B/G/P}"  # One black mana, one green mana, or 2 life
    BRP = "{B/R/P}"  # One black mana, one red mana, or 2 life
    GUP = "{G/U/P}"  # One green mana, one blue mana, or 2 life
    GWP = "{G/W/P}"  # One green mana, one white mana, or 2 life
    RGP = "{R/G/P}"  # One red mana, one green mana, or 2 life
    RWP = "{R/W/P}"  # One red mana, one white mana, or 2 life
    UBP = "{U/B/P}"  # One blue mana, one black mana, or 2 life
    URP = "{U/R/P}"  # One blue mana, one red mana, or 2 life
    WBP = "{W/B/P}"  # One white mana, one black mana, or 2 life
    WUP = "{W/U/P}"  # One white mana, one blue mana, or 2 life
    _2W = "{2/W}"  # Two generic mana or one white mana
    _2U = "{2/U}"  # Two generic mana or one blue mana
    _2B = "{2/B}"  # Two generic mana or one black mana
    _2R = "{2/R}"  # Two generic mana or one red mana
    _2G = "{2/G}"  # Two generic mana or one green mana
    P = "{P}"  # One colored mana or two life
    WP = "{W/P}"  # One white mana or two life
    UP = "{U/P}"  # One blue mana or two life
    BP = "{B/P}"  # One black mana or two life
    RP = "{R/P}"  # One red mana or two life
    GP = "{G/P}"  # One green mana or two life
    HW = "{HW}"  # One-half white mana
    HR = "{HR}"  # One-half red mana
    W = "{W}"  # One white mana
    U = "{U}"  # One blue mana
    B = "{B}"  # One black mana
    R = "{R}"  # One red mana
    G = "{G}"  # One green mana
    C = "{C}"  # One colorless mana
    S = "{S}"  # One snow mana
